main: glorydark.nukkit.customform.CustomFormMain
name: CustomForm
version: "1.5.3.8"
api: 1.0.0
author: Glorydark
description: CustomForm
depend:
  - GameAPI
softdepend:
  - DCurrency
  - EconomyAPI
  - Tips
  - RsNPC
  - LanguageAPI