main: glorydark.nukkit.customform.CustomFormMain
name: CustomForm
version: "1.3.7"
api: 1.0.0
author: Glorydark
description: CustomForm
softdepend:
  - DCurrency
  - EconomyAPI
  - Tips
  - RsNPC
  - LanguageAPI
  - GameAPI