main: glorydark.customform.CustomFormMain
name: CustomForm
version: "1.0.8.4"
api: 1.0.0
author: Glorydark
description: CustomForm
softdepend:
  - DCurrency
  - playerPoints
  - EconomyAPI
  - Tips
  - RsNPC