main: glorydark.nukkit.customform.CustomFormMain
name: CustomForm
version: "1.1.0.5"
api: 1.0.0
author: Glorydark
description: CustomForm
softdepend:
  - DCurrency
  - playerPoints
  - EconomyAPI
  - Tips
  - RsNPC