main: glorydark.customform.CustomFormMain
name: CustomForm
version: 1.0.6Candidate2
api: 1.0.0
author: Glorydark
description: CustomForm
softdepend:
  - DCurrency
  - playerPoints
  - EconomyAPI
  - Tips